#
# travis.yml
# Created by Felix Mau (https://felix.hamburg)
#

osx_image: xcode11
language: swift
script:
- ./Scripts/swift-format.sh
- ./Scripts/swift-lint.sh
- ./Scripts/pod-lint.sh
- ./Scripts/test.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
